### ISSUE TITLE
helol bro

### ISSUE THREAD

**Issue by yer7700** [kisman2000/python3d#1]
![image](https://user-images.githubusercontent.com/37212234/222736495-5c55433f-68e9-42a6-b368-7ddcb04131ee.png)

**Comment by kisman2000** [comment]
я ебал питон, я это начал писать только потому что мне нечего было делать на уроке, и продолжил дома все в чем проблема может когда ни будь потом я сделаю это нормально но щас бля я забыл что я написать хотел смейся так
